# Generated by Django 3.1.4 on 2021-05-20 13:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='streaming_service',
            field=models.CharField(default='spotify', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_of_room',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
