# Generated by Django 3.1.4 on 2021-05-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210520_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name_of_room',
            field=models.CharField(default='', max_length=12),
        ),
    ]
